image = "postgres"
version = "9.6.1"
root = "/var/lib/dokku/services/pg"
plugin_command_prefix = "pg"

#export PLUGIN_COMMAND_PREFIX="postgres"
#export PLUGIN_DATA_ROOT=$POSTGRES_ROOT
#export PLUGIN_DATASTORE_PORTS=(5432)
#export PLUGIN_DATASTORE_WAIT_PORT=5432
#export PLUGIN_DEFAULT_ALIAS="DATABASE"
#export PLUGIN_ALT_ALIAS="DOKKU_POSTGRES"
#export PLUGIN_IMAGE=$POSTGRES_IMAGE
#export PLUGIN_IMAGE_VERSION=$POSTGRES_IMAGE_VERSION
#export PLUGIN_SCHEME="postgres"
#export PLUGIN_SERVICE="Postgres"
#export PLUGIN_VARIABLE="POSTGRES"
#export PLUGIN_BASE_PATH="$PLUGIN_PATH"
#if [[ -n $DOKKU_API_VERSION ]]; then
#  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
#  fi

#if [[ -d "$PLUGIN_DATA_ROOT/*" ]]; then
#  rm -rf "${PLUGIN_DATA_ROOT:?}/*"
#  fi